package com.wickedstudios.wonderlot

/** The static content catalogue. All game objects are data; adding content means adding an entry here. */
object GameContent {
    // MARK: - Terrain

    // Walkway finishes. All the same walkway underneath: what changes is
    // what it is paved with, and a run can be repaved without being dug up.
    val path = TerrainDefinition(
        id = "path.concrete",
        displayName = "Walkway",
        summary = "Guests can only travel on walkways. Plain paving, and the cheapest way to get them anywhere.",
        purchasePrice = 25.0,
        refundValue = 10.0,
        terrain = TerrainType.path,
        placeableOn = setOf(TerrainType.grass, TerrainType.path, TerrainType.bridge),
        category = BuildCategory.path,
        beauty = 0.0,
        beautyRadius = 0
    )

    val brickPath = TerrainDefinition(
        id = "path.brick",
        displayName = "Brick Path",
        summary = "Warmer underfoot than concrete, and it makes an old-fashioned corner of the park look deliberate.",
        purchasePrice = 40.0,
        refundValue = 15.0,
        terrain = TerrainType.path,
        style = 1,
        placeableOn = setOf(TerrainType.grass, TerrainType.path, TerrainType.bridge),
        category = BuildCategory.path,
        beauty = 8.0,
        beautyRadius = 1
    )

    val boardwalk = TerrainDefinition(
        id = "path.boardwalk",
        displayName = "Boardwalk",
        summary = "Timber decking. Best round water, where it looks like it was always meant to be there.",
        purchasePrice = 45.0,
        refundValue = 18.0,
        terrain = TerrainType.path,
        style = 2,
        placeableOn = setOf(TerrainType.grass, TerrainType.path, TerrainType.bridge),
        category = BuildCategory.path,
        beauty = 10.0,
        beautyRadius = 1
    )

    val tarmac = TerrainDefinition(
        id = "path.tarmac",
        displayName = "Tarmac",
        summary = "Plain, dark and hard-wearing. Cheap enough to run to the far side of the lot.",
        purchasePrice = 20.0,
        refundValue = 8.0,
        terrain = TerrainType.path,
        style = 3,
        placeableOn = setOf(TerrainType.grass, TerrainType.path, TerrainType.bridge),
        category = BuildCategory.path,
        beauty = 0.0,
        beautyRadius = 0
    )

    val bridge = TerrainDefinition(
        id = "path.bridge",
        displayName = "Bridge",
        summary = "A deck across the water, with rails. The only way to walk guests over a pond instead of round it.",
        purchasePrice = 160.0,
        refundValue = 60.0,
        terrain = TerrainType.bridge,
        placeableOn = setOf(TerrainType.water),
        category = BuildCategory.path,
        beauty = 18.0,
        beautyRadius = 1
    )

    val water = TerrainDefinition(
        id = "terrain.water",
        displayName = "Pond",
        summary = "Ordinary park water. Build a bridge if you want guests on the other side of it.",
        purchasePrice = 90.0,
        refundValue = 20.0,
        terrain = TerrainType.water,
        placeableOn = setOf(TerrainType.grass, TerrainType.water),
        category = BuildCategory.scenery,
        beauty = 52.0,
        beautyRadius = 2
    )

    val lagoon = TerrainDefinition(
        id = "terrain.lagoon",
        displayName = "Lagoon",
        summary = "Bright turquoise, for the tropical corner of the park.",
        purchasePrice = 110.0,
        refundValue = 25.0,
        terrain = TerrainType.water,
        style = 1,
        placeableOn = setOf(TerrainType.grass, TerrainType.water),
        category = BuildCategory.scenery,
        beauty = 58.0,
        beautyRadius = 2
    )

    val deepWater = TerrainDefinition(
        id = "terrain.deepwater",
        displayName = "Deep Water",
        summary = "Dark and still. A big expanse of it reads as a lake rather than a puddle.",
        purchasePrice = 100.0,
        refundValue = 22.0,
        terrain = TerrainType.water,
        style = 2,
        placeableOn = setOf(TerrainType.grass, TerrainType.water),
        category = BuildCategory.scenery,
        beauty = 55.0,
        beautyRadius = 2
    )

    val coasterTrack = TerrainDefinition(
        id = "terrain.coastertrack",
        displayName = "Coaster Track",
        summary = "Lay your own circuit. The longer and the better it runs, the better the ride.",
        purchasePrice = 120.0,
        refundValue = 40.0,
        terrain = TerrainType.coasterTrack,
        category = BuildCategory.coaster,
        beauty = 0.0,
        beautyRadius = 0
    )

    // Terrain in build-menu order. Both are drawn by dragging, so they share
    // the same handling everywhere the player paints a run of tiles.
    val track = TerrainDefinition(
        id = "terrain.track",
        displayName = "Track",
        summary = "Railway for the trains. Drag out a loop, then put a station on it.",
        purchasePrice = 45.0,
        refundValue = 15.0,
        terrain = TerrainType.track,
        category = BuildCategory.transport,
        beauty = 0.0,
        beautyRadius = 0
    )

    // Terrain in build-menu order. All of it is drawn by dragging, so it
    // shares the same handling everywhere the player paints a run of tiles.
    val terrains: List<TerrainDefinition> = listOf(
        path, brickPath, boardwalk, tarmac, bridge,
        water, lagoon, deepWater,
        track, coasterTrack
    )

    // MARK: - Attractions

    val attractions: List<AttractionDefinition> = listOf(
        AttractionDefinition(
            id = "ride.carousel",
            displayName = "Carousel",
            summary = "A gentle spinning ride the whole family enjoys.",
            purchasePrice = 2500.0,
            capacity = 12,
            rideDuration = 45.0,
            loadDuration = 12.0,
            excitement = 20.0,
            nausea = 5.0,
            maintenanceRate = 0.010,
            operatingCostPerCycle = 4.0,
            footprint = GridSize(3, 3),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.carousel, ParkColour.pink, ParkColour.cream, ParkColour.amber),
            group = RideGroup.gentle
        ),
        AttractionDefinition(
            id = "ride.pirateship",
            displayName = "Swinging Galleon",
            summary = "A swinging boat that builds to a satisfying arc.",
            purchasePrice = 5000.0,
            capacity = 16,
            rideDuration = 60.0,
            loadDuration = 14.0,
            excitement = 50.0,
            nausea = 45.0,
            maintenanceRate = 0.020,
            operatingCostPerCycle = 8.0,
            footprint = GridSize(4, 3),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.swingBoat, ParkColour.red, ParkColour.sand, ParkColour.brown),
            group = RideGroup.thrill
        ),
        AttractionDefinition(
            id = "ride.droptower",
            displayName = "Sky Plunge",
            summary = "A slow climb, a long pause, then straight down.",
            purchasePrice = 8500.0,
            capacity = 12,
            rideDuration = 50.0,
            loadDuration = 16.0,
            excitement = 78.0,
            nausea = 50.0,
            maintenanceRate = 0.032,
            operatingCostPerCycle = 12.0,
            footprint = GridSize(3, 3),
            unlockLevel = 3,
            appearance = BuildingAppearance(BuildingMotif.dropTower, ParkColour.amber, ParkColour.sand, ParkColour.slate),
            group = RideGroup.thrill
        ),
        AttractionDefinition(
            id = "ride.minicoaster",
            displayName = "Sapling Coaster",
            summary = "A compact coaster with a surprising amount of bite.",
            purchasePrice = 15000.0,
            capacity = 16,
            rideDuration = 90.0,
            loadDuration = 20.0,
            excitement = 82.0,
            nausea = 42.0,
            maintenanceRate = 0.035,
            operatingCostPerCycle = 18.0,
            footprint = GridSize(6, 4),
            unlockLevel = 4,
            appearance = BuildingAppearance(BuildingMotif.coaster, ParkColour.yellow, ParkColour.lime, ParkColour.blue),
            group = RideGroup.thrill
        ),
        AttractionDefinition(
            id = "ride.teacups",
            displayName = "Spinning Teacups",
            summary = "Cheap, cheerful, and rougher on the stomach than it looks.",
            purchasePrice = 3200.0,
            capacity = 12,
            rideDuration = 40.0,
            loadDuration = 12.0,
            excitement = 32.0,
            nausea = 58.0,
            maintenanceRate = 0.012,
            operatingCostPerCycle = 5.0,
            footprint = GridSize(3, 3),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.teacups, ParkColour.violet, ParkColour.cream, ParkColour.pink),
            group = RideGroup.family
        ),
        AttractionDefinition(
            id = "ride.bumpercars",
            displayName = "Bumper Cars",
            summary = "A big draw for families, and almost nothing on it can break.",
            purchasePrice = 4200.0,
            capacity = 14,
            rideDuration = 55.0,
            loadDuration = 16.0,
            excitement = 42.0,
            nausea = 22.0,
            maintenanceRate = 0.014,
            operatingCostPerCycle = 7.0,
            footprint = GridSize(4, 3),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.bumperCars, ParkColour.blue, ParkColour.charcoal, ParkColour.yellow),
            group = RideGroup.family
        ),
        AttractionDefinition(
            id = "ride.carpetslide",
            displayName = "Carpet Slide",
            summary = "Four lanes, one hessian mat, and a queue that never stops moving.",
            purchasePrice = 5500.0,
            capacity = 10,
            rideDuration = 26.0,
            loadDuration = 10.0,
            excitement = 45.0,
            nausea = 14.0,
            maintenanceRate = 0.011,
            operatingCostPerCycle = 4.0,
            footprint = GridSize(4, 4),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.carpetSlide, ParkColour.orange, ParkColour.sand, ParkColour.yellow),
            group = RideGroup.family
        ),
        AttractionDefinition(
            id = "ride.gokarts.small",
            displayName = "Go Karts: Sprint",
            summary = "A short circuit. Two laps and they are queueing again.",
            purchasePrice = 6500.0,
            capacity = 8,
            rideDuration = 65.0,
            loadDuration = 22.0,
            excitement = 52.0,
            nausea = 20.0,
            maintenanceRate = 0.030,
            operatingCostPerCycle = 11.0,
            footprint = GridSize(4, 4),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.goKarts, ParkColour.red, ParkColour.lime, ParkColour.white),
            group = RideGroup.family
        ),
        AttractionDefinition(
            id = "ride.minigolf",
            displayName = "Wonder Putt",
            summary = "Eighteen holes squeezed into a corner of the park. Slow, cheap to run, "
                + "and it keeps a crowd occupied for ages.",
            purchasePrice = 6200.0,
            capacity = 16,
            // A round of crazy golf is the longest thing in the park that
            // nobody queues twice for, and it costs almost nothing to keep
            // running: there is no machinery, only grass.
            rideDuration = 130.0,
            loadDuration = 14.0,
            excitement = 34.0,
            nausea = 0.0,
            maintenanceRate = 0.005,
            operatingCostPerCycle = 3.0,
            footprint = GridSize(5, 4),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.miniGolf, ParkColour.green, ParkColour.cream, ParkColour.red),
            group = RideGroup.gentle
        ),
        AttractionDefinition(
            id = "ride.hauntedhouse",
            displayName = "Haunted Manor",
            summary = "A slow ride through the dark. Takes crowds, and takes them all day.",
            purchasePrice = 9000.0,
            capacity = 20,
            rideDuration = 95.0,
            loadDuration = 18.0,
            excitement = 56.0,
            nausea = 8.0,
            maintenanceRate = 0.016,
            operatingCostPerCycle = 10.0,
            footprint = GridSize(4, 4),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.hauntedHouse, ParkColour.indigo, ParkColour.charcoal, ParkColour.amber),
            group = RideGroup.gentle
        ),
        AttractionDefinition(
            id = "ride.ferriswheel",
            displayName = "Grand Wheel",
            summary = "Gentle, enormous capacity, and it makes the whole park look busier.",
            purchasePrice = 11000.0,
            capacity = 24,
            rideDuration = 110.0,
            loadDuration = 24.0,
            excitement = 40.0,
            nausea = 10.0,
            maintenanceRate = 0.018,
            operatingCostPerCycle = 12.0,
            footprint = GridSize(4, 4),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.ferrisWheel, ParkColour.cyan, ParkColour.red, ParkColour.white),
            group = RideGroup.gentle
        ),
        AttractionDefinition(
            id = "ride.gokarts.medium",
            displayName = "Go Karts: Circuit",
            summary = "A proper lap with a hairpin. Worth the ground it eats.",
            purchasePrice = 12000.0,
            capacity = 12,
            rideDuration = 95.0,
            loadDuration = 26.0,
            excitement = 64.0,
            nausea = 24.0,
            maintenanceRate = 0.038,
            operatingCostPerCycle = 17.0,
            footprint = GridSize(6, 5),
            unlockLevel = 3,
            appearance = BuildingAppearance(BuildingMotif.goKarts, ParkColour.amber, ParkColour.lime, ParkColour.white),
            group = RideGroup.thrill
        ),
        AttractionDefinition(
            id = "ride.slingshot",
            displayName = "Slingshot",
            summary = "Two riders, straight up. Nothing else in the park excites them more.",
            purchasePrice = 13500.0,
            capacity = 4,
            rideDuration = 34.0,
            loadDuration = 20.0,
            excitement = 93.0,
            nausea = 74.0,
            maintenanceRate = 0.048,
            operatingCostPerCycle = 14.0,
            footprint = GridSize(3, 3),
            unlockLevel = 4,
            appearance = BuildingAppearance(BuildingMotif.slingshot, ParkColour.yellow, ParkColour.slate, ParkColour.charcoal),
            group = RideGroup.thrill
        ),
        AttractionDefinition(
            id = "ride.logflume",
            displayName = "Log Flume",
            summary = "A long, wet circuit ending in a drop everyone stops to watch.",
            purchasePrice = 16000.0,
            capacity = 16,
            rideDuration = 105.0,
            loadDuration = 22.0,
            excitement = 70.0,
            nausea = 28.0,
            maintenanceRate = 0.034,
            operatingCostPerCycle = 16.0,
            footprint = GridSize(6, 5),
            unlockLevel = 3,
            appearance = BuildingAppearance(BuildingMotif.logFlume, ParkColour.cream, ParkColour.green, ParkColour.cyan),
            group = RideGroup.water
        ),
        AttractionDefinition(
            id = "ride.gokarts.large",
            displayName = "Go Karts: Grand Prix",
            summary = "The full track. Expensive to run, and guests talk about nothing else.",
            purchasePrice = 22000.0,
            capacity = 16,
            rideDuration = 130.0,
            loadDuration = 30.0,
            excitement = 74.0,
            nausea = 28.0,
            maintenanceRate = 0.046,
            operatingCostPerCycle = 26.0,
            footprint = GridSize(8, 6),
            unlockLevel = 4,
            appearance = BuildingAppearance(BuildingMotif.goKarts, ParkColour.indigo, ParkColour.slate, ParkColour.white),
            group = RideGroup.thrill
        ),
        AttractionDefinition(
            id = "ride.bigcoaster",
            displayName = "Thunder Coaster",
            summary = "The one people come for. It will also break more than anything else you own.",
            purchasePrice = 38000.0,
            capacity = 24,
            rideDuration = 125.0,
            loadDuration = 26.0,
            excitement = 96.0,
            nausea = 58.0,
            maintenanceRate = 0.052,
            operatingCostPerCycle = 34.0,
            footprint = GridSize(9, 6),
            unlockLevel = 4,
            appearance = BuildingAppearance(BuildingMotif.megaCoaster, ParkColour.red, ParkColour.charcoal, ParkColour.amber),
            group = RideGroup.thrill
        ),
        AttractionDefinition(
            id = "ride.mirrormaze",
            displayName = "Mirror Maze",
            summary = "Cheap, quiet, and it keeps a queue moving all day. Nothing on it can break.",
            purchasePrice = 2800.0,
            capacity = 14,
            rideDuration = 70.0,
            loadDuration = 10.0,
            excitement = 34.0,
            nausea = 6.0,
            maintenanceRate = 0.006,
            operatingCostPerCycle = 3.0,
            footprint = GridSize(3, 3),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.mirrorMaze, ParkColour.indigo, ParkColour.cyan, ParkColour.amber),
            group = RideGroup.gentle
        ),
        AttractionDefinition(
            id = "ride.fishingboats",
            displayName = "Fishing Boats",
            summary = "A slow lap of a reedy pond. Sits on the water, and calms a nauseous crowd.",
            purchasePrice = 4600.0,
            capacity = 12,
            rideDuration = 95.0,
            loadDuration = 16.0,
            excitement = 26.0,
            nausea = 2.0,
            maintenanceRate = 0.010,
            operatingCostPerCycle = 6.0,
            footprint = GridSize(5, 4),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.fishingBoats, ParkColour.cream, ParkColour.green, ParkColour.red),
            group = RideGroup.water,
            needsWater = true
        ),
        AttractionDefinition(
            id = "ride.bumperboats",
            displayName = "Bumper Boats",
            summary = "Bumper cars, wet. Sits on the water, and the queue never stops laughing.",
            purchasePrice = 6800.0,
            capacity = 12,
            rideDuration = 65.0,
            loadDuration = 18.0,
            excitement = 48.0,
            nausea = 18.0,
            maintenanceRate = 0.018,
            operatingCostPerCycle = 9.0,
            footprint = GridSize(4, 4),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.bumperBoats, ParkColour.teal, ParkColour.cyan, ParkColour.amber),
            group = RideGroup.water,
            needsWater = true
        ),
        AttractionDefinition(
            id = "ride.skygliders",
            displayName = "Sky Gliders",
            summary = "Chairs on a cable. Enormous capacity, almost no thrill, and everybody rides it once.",
            purchasePrice = 9500.0,
            capacity = 26,
            rideDuration = 115.0,
            loadDuration = 20.0,
            excitement = 38.0,
            nausea = 8.0,
            maintenanceRate = 0.020,
            operatingCostPerCycle = 11.0,
            footprint = GridSize(6, 3),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.skyGliders, ParkColour.cream, ParkColour.green, ParkColour.red),
            group = RideGroup.gentle
        ),
        AttractionDefinition(
            id = "ride.wavepool",
            displayName = "Wave Rider",
            summary = "A standing wave to surf. Sits on the water, and thrills without spinning anybody.",
            purchasePrice = 14000.0,
            capacity = 10,
            rideDuration = 60.0,
            loadDuration = 20.0,
            excitement = 72.0,
            nausea = 22.0,
            maintenanceRate = 0.038,
            operatingCostPerCycle = 18.0,
            footprint = GridSize(5, 4),
            unlockLevel = 3,
            appearance = BuildingAppearance(BuildingMotif.wavePool, ParkColour.slate, ParkColour.sand, ParkColour.cyan),
            group = RideGroup.water,
            needsWater = true
        ),
        AttractionDefinition(
            id = "ride.skyswings",
            displayName = "Sky Swings",
            summary = "Chairs on chains, flung out as it winds up. Half the park watches it go round.",
            purchasePrice = 5800.0,
            capacity = 16,
            rideDuration = 55.0,
            loadDuration = 14.0,
            excitement = 44.0,
            nausea = 30.0,
            maintenanceRate = 0.016,
            operatingCostPerCycle = 7.0,
            footprint = GridSize(3, 3),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.swingChairs, ParkColour.teal, ParkColour.cream, ParkColour.amber),
            group = RideGroup.family
        ),
        AttractionDefinition(
            id = "ride.lanterncruise",
            displayName = "Lantern Cruise",
            summary = "A slow loop of a lantern-lit canal. Takes a crowd, keeps it a long while, "
                + "and settles a stomach the teacups turned.",
            purchasePrice = 10500.0,
            capacity = 24,
            rideDuration = 120.0,
            loadDuration = 18.0,
            excitement = 34.0,
            nausea = 2.0,
            maintenanceRate = 0.009,
            operatingCostPerCycle = 8.0,
            footprint = GridSize(5, 4),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.lanternCruise, ParkColour.indigo, ParkColour.cream, ParkColour.amber),
            group = RideGroup.gentle
        ),
        AttractionDefinition(
            id = "ride.treetopzip",
            displayName = "Treetop Zip",
            summary = "One rider, one cable, one very long second. Narrow enough to tuck down a side path.",
            purchasePrice = 8800.0,
            capacity = 6,
            rideDuration = 30.0,
            loadDuration = 18.0,
            excitement = 76.0,
            nausea = 24.0,
            maintenanceRate = 0.026,
            operatingCostPerCycle = 9.0,
            footprint = GridSize(6, 3),
            unlockLevel = 3,
            appearance = BuildingAppearance(BuildingMotif.zipLine, ParkColour.lime, ParkColour.brown, ParkColour.cream),
            group = RideGroup.thrill
        ),
        AttractionDefinition(
            id = "ride.riverrapids",
            displayName = "River Rapids",
            summary = "Round rafts loose on white water. Nobody steers, and that is the appeal.",
            purchasePrice = 19000.0,
            capacity = 20,
            rideDuration = 110.0,
            loadDuration = 24.0,
            excitement = 68.0,
            nausea = 36.0,
            maintenanceRate = 0.032,
            operatingCostPerCycle = 19.0,
            footprint = GridSize(6, 5),
            unlockLevel = 3,
            appearance = BuildingAppearance(BuildingMotif.riverRapids, ParkColour.red, ParkColour.slate, ParkColour.cream),
            group = RideGroup.water
        ),
        AttractionDefinition(
            id = "ride.gravityhammer",
            displayName = "Gravity Hammer",
            summary = "A long arm that swings further every pass until it goes clean over the top. "
                + "Thrilling, punishing, and the most expensive thing in the park to keep running.",
            purchasePrice = 21000.0,
            capacity = 12,
            rideDuration = 55.0,
            loadDuration = 22.0,
            excitement = 90.0,
            nausea = 82.0,
            maintenanceRate = 0.050,
            operatingCostPerCycle = 22.0,
            footprint = GridSize(4, 4),
            unlockLevel = 4,
            appearance = BuildingAppearance(BuildingMotif.pendulumArm, ParkColour.violet, ParkColour.slate, ParkColour.amber),
            group = RideGroup.thrill
        ),
        AttractionDefinition(
            id = "coaster.station",
            displayName = "Wonder Coaster",
            summary = "Lay a circuit of coaster track and put this on it. A longer ride is a better ride.",
            purchasePrice = 12000.0,
            capacity = 20,
            rideDuration = 20.0,
            loadDuration = 20.0,
            excitement = 45.0,
            nausea = 40.0,
            maintenanceRate = 0.040,
            operatingCostPerCycle = 20.0,
            footprint = GridSize(4, 2),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.coasterStation, ParkColour.red, ParkColour.slate, ParkColour.amber),
            kind = AttractionKind.custom,
            group = RideGroup.thrill
        ),
        AttractionDefinition(
            id = "transport.station",
            displayName = "Train Station",
            summary = "Carries guests to another station on the same track. Cheap to run, and it saves a long walk.",
            purchasePrice = 4800.0,
            capacity = 20,
            rideDuration = 60.0,
            loadDuration = 18.0,
            excitement = 30.0,
            nausea = 4.0,
            maintenanceRate = 0.014,
            operatingCostPerCycle = 6.0,
            footprint = GridSize(3, 2),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.trainStation, ParkColour.green, ParkColour.cream, ParkColour.brown),
            kind = AttractionKind.transport
        )
    )

    // MARK: - Facilities

    val facilities: List<FacilityDefinition> = listOf(
        FacilityDefinition(
            id = "shop.burger",
            displayName = "Burger Stand",
            summary = "Hot food that takes a real bite out of hunger.",
            kind = FacilityKind.food,
            purchasePrice = 1200.0,
            defaultPrice = 7.0,
            unitCost = 3.0,
            referencePrice = 8.0,
            serviceDuration = 7.0,
            simultaneousCapacity = 1,
            queueCapacity = 10,
            relief = NeedRelief(hunger = 55.0, thirst = -10.0, bathroom = -12.0, happiness = 4.0),
            footprint = GridSize(2, 2),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.burgerStall, ParkColour.red, ParkColour.amber, ParkColour.brown)
        ),
        FacilityDefinition(
            id = "shop.popcorn",
            displayName = "Popcorn Cart",
            summary = "Bags of popcorn that guests carry round while they eat. Keep a bin close by: with none near, the empty bag goes on the ground, and the janitors pay for it.",
            kind = FacilityKind.food,
            purchasePrice = 800.0,
            defaultPrice = 4.0,
            unitCost = 0.8,
            referencePrice = 5.0,
            serviceDuration = 4.0,
            simultaneousCapacity = 1,
            queueCapacity = 8,
            relief = NeedRelief(hunger = 14.0, thirst = -16.0, happiness = 6.0),
            footprint = GridSize(1, 1),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.popcornCart, ParkColour.red, ParkColour.cream, ParkColour.amber),
            drawFactor = 1.15,
            carriesSnack = true
        ),
        FacilityDefinition(
            id = "shop.drinks",
            displayName = "Drink Kiosk",
            summary = "Cold drinks. Guests get thirsty faster than they get hungry.",
            kind = FacilityKind.drink,
            purchasePrice = 900.0,
            defaultPrice = 3.0,
            unitCost = 1.0,
            referencePrice = 4.0,
            serviceDuration = 5.0,
            simultaneousCapacity = 1,
            queueCapacity = 10,
            relief = NeedRelief(thirst = 65.0, bathroom = -20.0, happiness = 3.0),
            footprint = GridSize(2, 2),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.drinkKiosk, ParkColour.cyan, ParkColour.blue, ParkColour.indigo)
        ),
        FacilityDefinition(
            id = "shop.pizza",
            displayName = "Pizza Stand",
            summary = "Filling, and it makes guests thirsty afterwards.",
            kind = FacilityKind.food,
            purchasePrice = 1400.0,
            defaultPrice = 9.0,
            unitCost = 3.5,
            referencePrice = 10.0,
            serviceDuration = 8.0,
            simultaneousCapacity = 1,
            queueCapacity = 10,
            relief = NeedRelief(hunger = 62.0, thirst = -14.0, bathroom = -14.0, happiness = 5.0),
            footprint = GridSize(2, 2),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.pizzaStall, ParkColour.green, ParkColour.cream, ParkColour.red)
        ),
        FacilityDefinition(
            id = "shop.icecream",
            displayName = "Ice Cream Stand",
            summary = "Barely a meal, but it cheers guests up more than anything else.",
            kind = FacilityKind.food,
            purchasePrice = 1000.0,
            defaultPrice = 4.5,
            unitCost = 1.5,
            referencePrice = 5.0,
            serviceDuration = 5.0,
            simultaneousCapacity = 1,
            queueCapacity = 10,
            relief = NeedRelief(hunger = 22.0, thirst = 12.0, bathroom = -6.0, happiness = 11.0),
            footprint = GridSize(2, 2),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.iceCreamStall, ParkColour.pink, ParkColour.cream, ParkColour.violet)
        ),
        FacilityDefinition(
            id = "shop.souvenir",
            displayName = "Souvenir Shop",
            summary = "Happy guests with money left over buy something to take home.",
            kind = FacilityKind.souvenir,
            purchasePrice = 1800.0,
            defaultPrice = 14.0,
            unitCost = 5.0,
            referencePrice = 15.0,
            serviceDuration = 9.0,
            simultaneousCapacity = 1,
            queueCapacity = 8,
            relief = NeedRelief(happiness = 9.0),
            footprint = GridSize(2, 2),
            unlockLevel = 3,
            appearance = BuildingAppearance(BuildingMotif.souvenirShop, ParkColour.violet, ParkColour.indigo, ParkColour.amber)
        ),
        // MARK: Carnival games
        //
        // They all work the same way: a small price, a short go, and a chance
        // of walking out with something to carry round the park. What differs
        // is how likely that is and how much the go costs.
        FacilityDefinition(
            id = "game.basketball",
            displayName = "Hoop Shot",
            summary = "Three balls, two hoops. Easy to win, so guests keep coming back — for a keyring.",
            kind = FacilityKind.game,
            purchasePrice = 900.0,
            defaultPrice = 3.0,
            unitCost = 1.1,
            referencePrice = 3.5,
            serviceDuration = 9.0,
            simultaneousCapacity = 2,
            queueCapacity = 10,
            relief = NeedRelief(energy = -4.0, happiness = 9.0),
            footprint = GridSize(2, 2),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.basketballGame, ParkColour.orange, ParkColour.red, ParkColour.cream),
            winChance = 0.42
        ),
        FacilityDefinition(
            id = "game.balloons",
            displayName = "Balloon Poppers",
            summary = "Three darts at a wall of balloons. Loud, bright, and nearly everybody wins something.",
            kind = FacilityKind.game,
            purchasePrice = 1000.0,
            defaultPrice = 3.5,
            unitCost = 1.3,
            referencePrice = 4.0,
            serviceDuration = 8.0,
            simultaneousCapacity = 3,
            queueCapacity = 12,
            relief = NeedRelief(happiness = 10.0),
            footprint = GridSize(2, 2),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.balloonGame, ParkColour.violet, ParkColour.pink, ParkColour.cream),
            winChance = 0.48
        ),
        FacilityDefinition(
            id = "game.waterrace",
            displayName = "Water Gun Race",
            summary = "Five guests, five lanes, one winner. The queue moves fast because they all play at once, and the winner takes a big one.",
            kind = FacilityKind.game,
            purchasePrice = 1500.0,
            defaultPrice = 4.0,
            unitCost = 1.4,
            referencePrice = 4.5,
            serviceDuration = 11.0,
            simultaneousCapacity = 5,
            queueCapacity = 14,
            relief = NeedRelief(thirst = -6.0, happiness = 12.0),
            footprint = GridSize(3, 2),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.waterRaceGame, ParkColour.cyan, ParkColour.blue, ParkColour.cream),
            winChance = 0.30
        ),
        FacilityDefinition(
            id = "game.mole",
            displayName = "Whack-a-Mole",
            summary = "Sixty seconds of hitting things. Guests who have been queueing all day love it.",
            kind = FacilityKind.game,
            purchasePrice = 1600.0,
            defaultPrice = 4.0,
            unitCost = 1.5,
            referencePrice = 4.5,
            serviceDuration = 10.0,
            simultaneousCapacity = 2,
            queueCapacity = 10,
            relief = NeedRelief(energy = -6.0, happiness = 13.0),
            footprint = GridSize(2, 2),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.moleGame, ParkColour.lime, ParkColour.green, ParkColour.amber),
            winChance = 0.34
        ),
        FacilityDefinition(
            id = "game.ringtoss",
            displayName = "Ring Toss",
            summary = "Older than the park itself. Looks easy from the queue and is not, so the prizes are worth having.",
            kind = FacilityKind.game,
            purchasePrice = 800.0,
            defaultPrice = 3.0,
            unitCost = 1.0,
            referencePrice = 3.5,
            serviceDuration = 8.0,
            simultaneousCapacity = 2,
            queueCapacity = 10,
            relief = NeedRelief(happiness = 8.0),
            footprint = GridSize(2, 2),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.ringTossGame, ParkColour.teal, ParkColour.green, ParkColour.yellow),
            winChance = 0.24
        ),
        FacilityDefinition(
            id = "game.target",
            displayName = "Target Shooting",
            summary = "Steady hands only. The prizes are bigger because hardly anybody wins one.",
            kind = FacilityKind.game,
            purchasePrice = 1800.0,
            defaultPrice = 5.0,
            unitCost = 1.8,
            referencePrice = 5.5,
            serviceDuration = 12.0,
            simultaneousCapacity = 3,
            queueCapacity = 10,
            relief = NeedRelief(happiness = 11.0),
            footprint = GridSize(3, 2),
            unlockLevel = 3,
            appearance = BuildingAppearance(BuildingMotif.targetGame, ParkColour.indigo, ParkColour.charcoal, ParkColour.amber),
            winChance = 0.20
        ),
        FacilityDefinition(
            id = "game.whammy",
            displayName = "Wonder Whammy",
            summary = "One swing of the hammer. Ring the bell and you walk away with something you need both arms for.",
            kind = FacilityKind.game,
            purchasePrice = 2200.0,
            defaultPrice = 6.0,
            unitCost = 2.2,
            referencePrice = 6.5,
            serviceDuration = 9.0,
            simultaneousCapacity = 1,
            queueCapacity = 10,
            relief = NeedRelief(energy = -8.0, happiness = 15.0),
            footprint = GridSize(2, 2),
            unlockLevel = 3,
            appearance = BuildingAppearance(BuildingMotif.strengthTester, ParkColour.red, ParkColour.charcoal, ParkColour.amber),
            winChance = 0.22
        ),
        FacilityDefinition(
            id = "facility.bathroom",
            displayName = "Restroom",
            summary = "Guests get unhappy fast when they cannot find one.",
            kind = FacilityKind.bathroom,
            purchasePrice = 1500.0,
            defaultPrice = 0.0,
            unitCost = 0.0,
            referencePrice = 0.0,
            serviceDuration = 22.0,
            simultaneousCapacity = 2,
            queueCapacity = 12,
            relief = NeedRelief(bathroom = 100.0, happiness = 3.0),
            footprint = GridSize(2, 2),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.restroom, ParkColour.cream, ParkColour.teal, ParkColour.slate),
            cleaningMinutes = 15.0
        ),
        FacilityDefinition(
            id = "facility.luxurybathroom",
            displayName = "Luxury Washroom",
            summary = "Marble, attendants and room for a crowd. Guests come out happier, it counts for far more towards the park rating, and it stays cleaner for longer. It also takes a janitor nearly twice as long to turn round, and is shut the whole time.",
            kind = FacilityKind.bathroom,
            purchasePrice = 7500.0,
            defaultPrice = 0.0,
            unitCost = 0.0,
            referencePrice = 0.0,
            serviceDuration = 24.0,
            simultaneousCapacity = 6,
            queueCapacity = 20,
            relief = NeedRelief(bathroom = 100.0, happiness = 14.0, nausea = 20.0),
            footprint = GridSize(3, 2),
            unlockLevel = 3,
            appearance = BuildingAppearance(BuildingMotif.luxuryRestroom, ParkColour.cream, ParkColour.amber, ParkColour.teal),
            drawFactor = 1.6,
            cleaningMinutes = 27.0,
            soilingPerUse = 3.2,
            ratingWeight = 2.5
        ),
        FacilityDefinition(
            id = "facility.bench",
            displayName = "Bench",
            summary = "Goes straight on the walkway. Tired guests sit here instead of going home early.",
            kind = FacilityKind.bench,
            purchasePrice = 120.0,
            defaultPrice = 0.0,
            unitCost = 0.0,
            referencePrice = 0.0,
            serviceDuration = 40.0,
            simultaneousCapacity = 2,
            queueCapacity = 2,
            relief = NeedRelief(energy = 45.0, happiness = 2.0, nausea = 25.0),
            footprint = GridSize(1, 1),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.bench, ParkColour.brown, ParkColour.sand, ParkColour.charcoal)
        ),
        FacilityDefinition(
            id = "facility.picnic",
            displayName = "Picnic Table",
            summary = "Goes on the walkway. Seats a family at once, and they eat what they bought at your stalls instead of taking it home.",
            kind = FacilityKind.bench,
            purchasePrice = 260.0,
            defaultPrice = 0.0,
            unitCost = 0.0,
            referencePrice = 0.0,
            serviceDuration = 50.0,
            simultaneousCapacity = 4,
            queueCapacity = 4,
            relief = NeedRelief(hunger = 8.0, energy = 55.0, happiness = 4.0, nausea = 28.0),
            footprint = GridSize(1, 1),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.picnicTable, ParkColour.teal, ParkColour.cream, ParkColour.brown)
        ),
        FacilityDefinition(
            id = "facility.bin",
            displayName = "Garbage Bin",
            summary = "On the walkway or on the grass beside one. Without bins, "
                + "guests carrying rubbish drop it.",
            kind = FacilityKind.bin,
            purchasePrice = 80.0,
            defaultPrice = 0.0,
            unitCost = 0.0,
            referencePrice = 0.0,
            serviceDuration = 2.0,
            simultaneousCapacity = 1,
            queueCapacity = 4,
            relief = NeedRelief(),
            footprint = GridSize(1, 1),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.bin, ParkColour.slate, ParkColour.charcoal, ParkColour.amber)
        )
    )

    // MARK: - Scenery

    val scenery: List<SceneryDefinition> = listOf(
        SceneryDefinition(
            id = "scenery.tree",
            displayName = "Shade Tree",
            summary = "Cheap greenery. A row of them turns a bare walkway into somewhere pleasant.",
            purchasePrice = 150.0,
            beauty = 30.0,
            beautyRadius = 2,
            footprint = GridSize(1, 1),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.tree, ParkColour.green, ParkColour.lime, ParkColour.brown)
        ),
        SceneryDefinition(
            id = "scenery.conifer",
            displayName = "Pine",
            summary = "Taller and darker than a shade tree, and reaches a little further.",
            purchasePrice = 220.0,
            beauty = 38.0,
            beautyRadius = 2,
            footprint = GridSize(1, 1),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.conifer, ParkColour.teal, ParkColour.green, ParkColour.brown)
        ),
        SceneryDefinition(
            id = "scenery.flowerbed",
            displayName = "Flower Bed",
            summary = "Low colour beside a path. Best in clusters where guests queue.",
            purchasePrice = 180.0,
            beauty = 34.0,
            beautyRadius = 1,
            footprint = GridSize(1, 1),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.flowerBed, ParkColour.pink, ParkColour.yellow, ParkColour.brown)
        ),
        SceneryDefinition(
            id = "scenery.lilypads",
            displayName = "Lily Pads",
            summary = "Floats on the water. A pond with nothing on it looks empty; this fixes that cheaply.",
            purchasePrice = 260.0,
            beauty = 28.0,
            beautyRadius = 2,
            footprint = GridSize(2, 2),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.lilyPads, ParkColour.green, ParkColour.pink, ParkColour.lime),
            onWater = true
        ),
        SceneryDefinition(
            id = "scenery.reeds",
            displayName = "Reeds",
            summary = "A stand of cattails for the water. Small, cheap, and a pond looks wrong without them.",
            purchasePrice = 140.0,
            beauty = 22.0,
            beautyRadius = 1,
            footprint = GridSize(1, 1),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.reeds, ParkColour.green, ParkColour.brown, ParkColour.lime),
            onWater = true
        ),
        SceneryDefinition(
            id = "scenery.waterrock",
            displayName = "Water Rock",
            summary = "Mossy boulders breaking the surface, with foam at their feet. Makes a pond look as if it has always been there.",
            purchasePrice = 420.0,
            beauty = 44.0,
            beautyRadius = 3,
            footprint = GridSize(2, 2),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.waterRock, ParkColour.slate, ParkColour.green, ParkColour.white),
            onWater = true
        ),
        SceneryDefinition(
            id = "scenery.waterlanterns",
            displayName = "Floating Lanterns",
            summary = "Paper lanterns drifting on the pond. Best seen at the end of the day.",
            purchasePrice = 380.0,
            beauty = 40.0,
            beautyRadius = 2,
            footprint = GridSize(2, 1),
            unlockLevel = 3,
            appearance = BuildingAppearance(BuildingMotif.floatingLanterns, ParkColour.red, ParkColour.amber, ParkColour.cream),
            onWater = true
        ),
        SceneryDefinition(
            id = "scenery.pondfountain",
            displayName = "Pond Fountain",
            summary = "A stone ring and a jet, set in the water itself. The showpiece of a pond.",
            purchasePrice = 1600.0,
            beauty = 66.0,
            beautyRadius = 3,
            footprint = GridSize(2, 2),
            unlockLevel = 3,
            appearance = BuildingAppearance(BuildingMotif.pondFountain, ParkColour.slate, ParkColour.cream, ParkColour.sand),
            onWater = true
        ),
        SceneryDefinition(
            id = "scenery.lamp",
            displayName = "Park Lamp",
            summary = "Modest on its own, but it tidies up a long stretch of walkway.",
            purchasePrice = 120.0,
            beauty = 20.0,
            beautyRadius = 2,
            footprint = GridSize(1, 1),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.lamp, ParkColour.amber, ParkColour.cream, ParkColour.charcoal)
        ),
        SceneryDefinition(
            id = "scenery.topiary",
            displayName = "Topiary",
            summary = "Clipped hedging in a planter. Smart enough for a park entrance.",
            purchasePrice = 320.0,
            beauty = 46.0,
            beautyRadius = 2,
            footprint = GridSize(1, 1),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.topiary, ParkColour.green, ParkColour.lime, ParkColour.sand)
        ),
        SceneryDefinition(
            id = "scenery.statue",
            displayName = "Statue",
            summary = "A landmark. Expensive, and worth it where everybody walks past.",
            purchasePrice = 1400.0,
            beauty = 70.0,
            beautyRadius = 3,
            footprint = GridSize(1, 1),
            unlockLevel = 3,
            appearance = BuildingAppearance(BuildingMotif.statue, ParkColour.cream, ParkColour.amber, ParkColour.slate)
        ),
        SceneryDefinition(
            id = "scenery.hedge",
            displayName = "Hedge",
            summary = "Edging. A run of them turns a walkway into a route rather than a line on the grass.",
            purchasePrice = 90.0,
            beauty = 16.0,
            beautyRadius = 1,
            footprint = GridSize(1, 1),
            unlockLevel = 1,
            appearance = BuildingAppearance(BuildingMotif.hedge, ParkColour.green, ParkColour.lime, ParkColour.brown)
        ),
        SceneryDefinition(
            id = "scenery.flagpole",
            displayName = "Flag Pole",
            summary = "Flies the park's colours. Tall enough to be seen from the far side of the lot.",
            purchasePrice = 380.0,
            beauty = 40.0,
            beautyRadius = 2,
            footprint = GridSize(1, 1),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.flagPole, ParkColour.teal, ParkColour.cream, ParkColour.slate)
        ),
        SceneryDefinition(
            id = "scenery.arch",
            displayName = "Garden Arch",
            summary = "Goes over the path itself. Two of them at either end make it look designed.",
            purchasePrice = 460.0,
            beauty = 50.0,
            beautyRadius = 2,
            footprint = GridSize(1, 1),
            unlockLevel = 2,
            appearance = BuildingAppearance(BuildingMotif.gardenArch, ParkColour.teal, ParkColour.lime, ParkColour.cream),
            spansWalkway = true
        ),
        SceneryDefinition(
            id = "scenery.clocktower",
            displayName = "Clock Tower",
            summary = "The tallest thing in the park nobody queues for, and the one everybody meets at.",
            purchasePrice = 2600.0,
            beauty = 86.0,
            beautyRadius = 4,
            footprint = GridSize(2, 2),
            unlockLevel = 3,
            appearance = BuildingAppearance(BuildingMotif.clockTower, ParkColour.teal, ParkColour.amber, ParkColour.cream)
        ),
        SceneryDefinition(
            id = "scenery.fountain",
            displayName = "Fountain",
            summary = "The centrepiece. Nothing else lifts the look of a park this much.",
            purchasePrice = 3200.0,
            beauty = 100.0,
            beautyRadius = 4,
            footprint = GridSize(2, 2),
            unlockLevel = 3,
            appearance = BuildingAppearance(BuildingMotif.fountain, ParkColour.cyan, ParkColour.white, ParkColour.slate)
        )
    )


    // MARK: - Lookup

    private val attractionsByID: Map<String, AttractionDefinition> by lazy { attractions.associateBy { it.id } }
    private val facilitiesByID: Map<String, FacilityDefinition> by lazy { facilities.associateBy { it.id } }
    private val sceneryByID: Map<String, SceneryDefinition> by lazy { scenery.associateBy { it.id } }

    fun attraction(id: String): AttractionDefinition? = attractionsByID[id]
    fun facility(id: String): FacilityDefinition? = facilitiesByID[id]
    fun scenery(id: String): SceneryDefinition? = sceneryByID[id]

    /** Everything placeable, in menu order. */
    val allBuildables: List<BuildableDefinition> by lazy {
        val result = ArrayList<BuildableDefinition>()
        result.addAll(terrains)
        result.addAll(attractions)
        result.addAll(facilities)
        result.addAll(CoasterElementContent.all)
        result.addAll(scenery)
        result
    }

    fun buildables(category: BuildCategory, unlockLevel: Int): List<BuildableDefinition> =
        allBuildables.filter { it.category == category && it.unlockLevel <= unlockLevel }
}
